#LOGGING
logging:
    config: classpath:config/logback.xml
hsweb:
    dynamic-datasource: #动态数据源配置
          url : jdbc:mysql://123.56.11.62:3306/hsweb-demo?useUnicode=true&amp;characterEncoding=utf8&allowMultiQueries=true
          username : root
          password : uAiqwVwjJ8-iguojian
          driver-class-name : com.mysql.jdbc.Driver
          icatch:
            max-actives: 100
            output-dir: ./data/atomikos
            log_base_dir: ./data/atomikos
            default-jta-timeout: 300000
    access-logger: on
spring:
  redis:
    host: localhost
scheduler:
  properties:
    org.quartz.jobStore.selectWithLockSQL: SELECT * FROM {0}LOCKS UPDLOCK WHERE LOCK_NAME = ?